stages:
    - format
    - env

variables:
    VENV: "/home/gitlab-runner/venv-cinfer-ci"
    GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - export CUR_COMMIT_ID=$(git rev-parse HEAD)

############################################################################################################
# Format

format_check:
    stage: format
    only:
        - merge_requests
    tags:
        - dev
    script:
        - source $VENV/bin/activate
        - pip install black -i https://pypi.tuna.tsinghua.edu.cn/simple
        - black --exclude src/third_party/ --exclude third_party/ --check .
        - source /home/spack/spack/share/spack/setup-env.sh
        - spack load --first llvm
        - find . -type f \( -name '*.cc' -o -name '*.cu' -o -name '*.h' \) -exec clang-format --dry-run -Werror {} +

############################################################################################################
# Build
env_build_ascend:
  stage: env
  only:
    - merge_requests
  tags:
    - huawei-4-910B
  needs:
    - format_check
  script:
    - CI_WORKSPACE=$(pwd)
    - |
      grun 8 docker run --rm \
      --name ${CUR_COMMIT_ID} \
      --device /dev/davinci0 \
      --device /dev/davinci1 \
      --device /dev/davinci2 \
      --device /dev/davinci3 \
      --device /dev/davinci4 \
      --device /dev/davinci5 \
      --device /dev/davinci6 \
      --device /dev/davinci7 \
      --device /dev/davinci_manager \
      --device /dev/devmm_svm \
      --device /dev/hisi_hdc \
      -v "${CI_WORKSPACE}:/workspace" \
      -w /workspace \
      -v /usr/local/dcmi:/usr/local/dcmi \
      -v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi \
      -v /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/ \
      -v /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info \
      -v /etc/ascend_install.info:/etc/ascend_install.info \
      quay.io/ascend/vllm-ascend:v0.8.5rc1 bash -c "cd /workspace/grouped_gemm && pip install . && cd test && bash run_test.sh"

